services:
  backend:
    build:
      context: ./backend
      network: host
    restart: unless-stopped
    networks:
      - tlm-net

  frontend:
    build:
      context: ./frontend
      network: host
    restart: unless-stopped
    ports:
      - "3030:80"
    depends_on:
      - backend
    networks:
      - tlm-net

networks:
  tlm-net:
    driver: bridge